TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  eval_steps: 1
  gradient_accumulation_steps: 10
  evaluation_strategy: steps
  save_steps: 10000
