# TrainingArguments:
#   num_train_epochs: 1
#   warmup_steps: 500
#   per_device_train_batch_size: 1
#   weight_decay: 0.01
#   logging_steps: 10
#   eval_steps: 1
#   gradient_accumulation_steps: 4
#   evaluation_strategy: steps
#   save_steps: 10000

TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 0
  per_device_train_batch_size: 4
  weight_decay: 0.01
  logging_steps: 50
  eval_steps: 100
  gradient_accumulation_steps: 1
  evaluation_strategy: "no"
  save_steps: 0

  # num_train_epochs: 1
  # warmup_steps: 50
  # per_device_train_batch_size: 1
  # weight_decay: 0.01
  # logging_steps: 5
  # eval_steps: 1
  # gradient_accumulation_steps: 1
  # evaluation_strategy: steps
  # save_steps: 5
